version: '3'
services:
  arch:
    build: ./spack_arch
    volumes:
      - '../../..:/spack'
    environment:
      PROMPT: "${PROMPT:-0}"
  centos:
    build: ./spack_centos
    volumes:
      - '../../..:/spack'
    environment:
      PROMPT: "${PROMPT:-0}"
  fedora:
    build: ./spack_fedora
    volumes:
      - '../../..:/spack'
    environment:
      PROMPT: "${PROMPT:-0}"
  opensuse:
    build: ./spack_opensuse
    volumes:
      - '../../..:/spack'
    environment:
      PROMPT: "${PROMPT:-0}"
  ubuntu:
    build: ./spack_ubuntu
    volumes:
      - '../../..:/spack'
    environment:
      PROMPT: "${PROMPT:-0}"
